version: '3.7'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=1
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MYSQL_HOST=db
      - MYSQL_PORT=${MYSQL_PORT}
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

volumes:
  mysql_db:
