# Generated by Django 5.0.3 on 2024-03-22 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
