# Generated by Django 5.0.3 on 2024-03-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("lesson", "user")},
        ),
    ]
